# Generated by Django 4.1.2 on 2022-10-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_favorite_id_alter_ingredient_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="static/recipe/",
                verbose_name="Изображение",
            ),
        ),
    ]
